spring:
  application:
    name: be-foreigner
  datasource:
    url: jdbc:mysql://localhost:3306/be-foreigner?createDatabaseIfNotExist=true&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: be-foreigner
    password: password

  profiles:
    active:
    - dev
    - prod
    default: dev
  
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
        
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  output:
    ansi:
      enabled: always

application:
  notification:
    app-icon: https://res.cloudinary.com/dqzwh7zvo/image/upload/v1726656428/be-foreigner-icon.png
    
  auth:
    admin-user: 
      username: admin
      password: password
      email: admin@gmail.com
      fullname: adminitrastor
    jwt:
      issuer: "beforeigner.huce.edu.vn"
      expireDuration: "10m"
      secretKey: "adjzfjdfndjmfgbdvjkfbzjxfn1o2u4q90wafheskedd"