spring:
  application:
    name: be-foreigner
  datasource:
    url: jdbc:mysql://localhost:3306/be-foreigner?createDatabaseIfNotExist=true&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: be-foreigner
    password: password

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode:  never
      encoding: UTF-8
      
application:
  notification:
    app-icon: https://res.cloudinary.com/dqzwh7zvo/image/upload/v1726656428/be-foreigner-icon.png
  mail:
    admin-mail: codedaovoiduy@gmail.com
  auth:
    jwt:
      issuer: "beforeigner.huce.edu.vn"
      expire-duration: "10d"
      secret-key: adjzfjdfndjmfgbdvjkfbzjxfn1o2u4q90wafheskedd
