spring:
  application:
    name: be-foreigner
  datasource:
    url: jdbc:mysql://localhost:3306/be-foreigner-dev?createDatabaseIfNotExist=true&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: be-foreigner
    password: password
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
    # jakarta:
    #   persistence:
    #     schema-generation:
    #       scripts:
    #         action: create
    #         create-target: metadata.sql
    hibernate:
      ddl-auto: update
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: never
      encoding: UTF-8
      
application:
  notification:
    app-icon: https://res.cloudinary.com/dqzwh7zvo/image/upload/v1733234774/d1tru2gdki7aewmricar.png
    
  mail:
    admin-mail: codedaovoiduy@gmail.com
  auth:
    jwt:
      issuer: "beforeigner.huce.edu.vn"
      expire-duration: "10d"
      secret-key: adjzfjdfndjmfgbdvjkfbzjxfn1o2u4q90wafheskedd
